import { IRestaurant } from "@/types/common"

interface IRestConf {
    restaurants: IRestaurant[]
}

export const restConf: IRestConf = {
    restaurants: [
        {
            address: "10.20.30.2",
            port: 86,
            name: "Лондон",
            id: 30,
            username: "Wilde",
            password: "1024",
        },
        {
            address: "10.20.4.2",
            port: 86,
            name: "Сизон",
            id: 4,
            username: "Wilde",
            password: "1024",
        },
        {
            address: "10.20.4.2",
            port: 885,
            name: "Шампань",
            id: 27,
            username: "Wilde",
            password: "1024",
        },
        {
            address: "10.20.1.2",
            port: 86,
            name: "Барселонета",
            id: 1,
            username: "Wilde",
            password: "1024",
        },
        {
            address: "10.20.31.2",
            port: 86,
            name: "Сибас",
            id: 31,
            username: "Wilde",
            password: "1024",
        },
        {
            address: "10.20.2.2",
            port: 86,
            name: "ЯпонаМама",
            id: 5,
            username: "Wilde",
            password: "1101",
            ident: 1001847,
            type: "big",
        },
        {
            address: "10.20.5.2",
            port: 86,
            name: "ХмелиСунели",
            id: 6,
            username: "Wilde",
            password: "1101",
            ident: 1005084,
            type: "big",
        },
        {
            address: "10.20.3.2",
            port: 86,
            name: "Синдикат",
            id: 3,
            username: "Wilde",
            password: "1101",
            ident: 1096511,
            type: "big",
        },
        {
            address: "10.20.2.2",
            port: 86,
            name: "Магелан",
            id: 25,
            username: "Wilde",
            password: "1101",
            ident: 1016367,
            type: "big",
        },
        {
            address: "10.20.2.2",
            port: 86,
            name: "Мамино",
            id: 18,
            username: "Wilde",
            password: "1101",
            ident: 1229934,
            type: "big",
        },
        {
            address: "10.20.2.2",
            port: 86,
            name: "Роз Лавка",
            id: 19,
            username: "Wilde",
            password: "1101",
            ident: 1009264,
            type: "big",
        },
        {
            address: "10.20.2.2",
            port: 86,
            name: "Кондитерский Бутик",
            id: 20,
            username: "Wilde",
            password: "1101",
            ident: 1096509,
            type: "big",
        },
    ],
}
